Repository SysBioChalmers/GECKO, pull requests merged in 2018-12, with the labels that each got.

#61 refactor/feat: topUsedEnzymes, truncateValues and modifyKcats
  geckomat/kcat_sensitivity_analysis/modifyKcats.m
  geckomat/kcat_sensitivity_analysis/topUsedEnzymes.m
  geckomat/kcat_sensitivity_analysis/truncateValues.m
  geckomat/limit_proteins/getConstrainedModel.m
Labels: enhancement, format

#64 feat: added getSubset_ecModel
  geckomat/utilities/getSubset_ecModel.m
Labels: enhancement

#67 feat: new function getKcat
  geckomat/utilities/getKcat.m
Labels: enhancement

#68 fix: change EOL characters to Unix
  geckomat/get_enzyme_data/findInDB.m
  geckomat/get_enzyme_data/flattenCell.m
  geckomat/get_enzyme_data/getEnzymeCodes.m
  geckomat/kcat_sensitivity_analysis/modifyKcats.m
  geckomat/kcat_sensitivity_analysis/topUsedEnzymes.m
  geckomat/kcat_sensitivity_analysis/truncateValues.m
  geckomat/limit_proteins/constrainPool.m
  geckopy/docs/make.bat
Labels: bug, format
