Repository SysBioChalmers/GECKO, pull requests merged in 2020-11, with the labels that each got.

#110 fix: update envlist in CI
  .travis.yml
  README.rst
  geckopy/tox.ini
Labels: bug, geckopy

#113 Fix/ec model versioning
  geckomat/change_model/preprocessModel.m
  geckomat/enhanceGEM.m
Labels: bug

#115 Feat/guidelines
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-detected.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new-feature.md
  .github/pull_request_template.md
  README.rst
  geckopy/.github/CONTRIBUTING.rst
  geckopy/.github/ISSUE_TEMPLATE.md
  geckopy/.github/PULL_REQUEST_TEMPLATE.md
  geckopy/.github/SUPPORT.rst
Labels: documentation
