Repository SysBioChalmers/GECKO, pull requests merged in 2021-01, with the labels that each got.

#124 fix: allow empty prot_abundance.txt files
  geckomat/limit_proteins/measureAbundance.m
Labels: bug

#127 Fix/updates to getSubset_ecModel
  geckomat/utilities/getSubset_ecModel.m
Labels: bug, enhancement

#120 Feat/get_subset_ecModel
  geckomat/utilities/getSubset_ecModel.m
Labels: enhancement
